#Configuración del sitio
title: Compumundo Hipermegarred
email: mamurciac@unal.edu.co
url: https://compumundohipermegarred.github.io
description: "En esta página podrás encontrar notas detalladas de clase de las materias de ingeniería de sistemas. Este material consiste en una recopilación de apuntes de distintas referencias bibliográficas, tanto de libros como de cursos en línea y algunas páginas web."
keywords: "Cálculo, Datos, Información, Ingeniería, Programación, Sistemas"
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Michael Andrés Murcia Contreras
meta_email: mamurciac@unal.edu.co

#Verificación de la página en el buscador de Google (Con Google Webmaster Tools)
#google_verify:

#Verificación de la página en el buscador de Bing. Enlace de apoyo: https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

#Formulario de Contacto:
#  - static: Se valida el envió del mensaje de correo electrónico con Formspree.io
#  - disqus: Se reemplaza el formulario de contacto por el hilo de Disqus
#Para mantener el formulario de contacto de PHP predeterminado, se comenta la próxima línea
contact: static

#Si se utiliza disqus, es necesario el nombre breve de la página en disqus
#https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

#Ajustes de Color (En codificación hexadecimal sin la etiqueta de hashtag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

#Ajustes de pie de página
footer:
  copyright: El conocimiento es la mejor inversión que se puede hacer (Abraham Lincoln)
  location: Ubicación
  social: En la Web
  credits: Créditos

#Nombres de usuario para Redes Sociales (Hay varias disponibles como: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/Compumundo-Hipermegarred-894115067409624/
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/CompumundoHipermegarred/CompumundoHipermegarred.github.io

#Dirección Postal (Se pueden añadir cuantas líneas sean necesarias)
address:
  - line: Universidad Nacional
  - line: Bogotá D.C., Colombia

#Contenido de los créditos
credits: 'La plantilla (<a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a> de Jekyll) sobre la cual se construyó la página es Freelancer es de uso libre, y las notas de clase son tomadas a partir de apuntes de distintas referencias bibliográficas, tanto de libros como de cursos en línea y algunas páginas web. En la bibliografía de cada asignatura se ilustran las referencias citadas en detalle.'

#Ajustes de compilación
markdown: kramdown
permalink: pretty
